# Generated by Django 5.1.4 on 2024-12-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('company_name', models.CharField(max_length=255)),
                ('employees', models.JSONField()),
                ('positions', models.JSONField()),
                ('location', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
