# Generated by Django 5.1 on 2024-08-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('A', 'Attack Helicopter')], default='Attack Helicopter', max_length=1),
        ),
    ]
