# Generated by Django 5.1 on 2024-08-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_created_at_alter_author_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
